# Generated by Django 3.0.2 on 2020-04-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.AddField(
            model_name='register',
            name='gender_female',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='register',
            name='gender_male',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
        migrations.AddField(
            model_name='register',
            name='gender_other',
            field=models.BooleanField(default=False, verbose_name='Other'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='register',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register.Location'),
            preserve_default=False,
        ),
    ]
