# Generated by Django 3.0.2 on 2020-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200429_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='profession',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
